services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 16379:6379
    volumes:
      - redis:/data
  
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: AliceZ0317
      MYSQL_DATABASE: cron-job-dash
    volumes:
      - mysql:/var/lib/mysql
volumes:
  redis:
    driver: local
  mysql:
